# Generated by Django 5.1.6 on 2025-07-09 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dreams",
            "0010_alter_chatmessage_options_alter_chatmessage_receiver_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="成就名稱"
                    ),
                ),
                ("description", models.TextField(verbose_name="成就描述")),
                (
                    "category",
                    models.CharField(
                        default="General", max_length=50, verbose_name="類別"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="稱號"
                    ),
                ),
                (
                    "badge_icon",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="徽章圖標"
                    ),
                ),
                (
                    "condition_key",
                    models.CharField(max_length=50, verbose_name="條件鍵"),
                ),
                (
                    "condition_value",
                    models.IntegerField(default=1, verbose_name="條件值"),
                ),
            ],
            options={
                "verbose_name": "成就",
                "verbose_name_plural": "成就",
                "ordering": ["condition_value"],
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="current_badge_icon",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="當前徽章圖標"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="current_title",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="當前稱號"
            ),
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unlocked_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="解鎖時間"),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dreams.achievement",
                        verbose_name="成就",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用戶",
                    ),
                ),
            ],
            options={
                "verbose_name": "用戶成就",
                "verbose_name_plural": "用戶成就",
                "unique_together": {("user", "achievement")},
            },
        ),
    ]
