# Generated by Django 5.1.6 on 2025-07-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0020_therapyappointment_point_change"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapyappointment",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
