# Generated by Django 5.1.6 on 2025-09-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0031_dreamshare"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="proof_file",
            field=models.FileField(
                blank=True, null=True, upload_to="therapist_proofs/"
            ),
        ),
    ]
