# Generated by Django 5.1.7 on 2025-03-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dream",
            name="emotion_score",
            field=models.FloatField(default=0, verbose_name="情緒得分"),
        ),
        migrations.AddField(
            model_name="dream",
            name="stress_index",
            field=models.IntegerField(default=0, verbose_name="壓力指數"),
        ),
    ]
