# Generated by Django 5.1.6 on 2025-09-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='proofs/'),
        ),
    ]