# Generated by Django 5.1.6 on 2025-06-30 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dreampost",
            name="is_flagged",
        ),
    ]
