# Generated by Django 5.1.6 on 2025-09-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0002_auto_20250908_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='therapist_proofs/'),
        ),
    ]
