# Generated by Django 5.1.6 on 2025-07-25 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0002_therapyappointment_is_cancelled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='displayed_by_badge', to='dreams.achievement', verbose_name='社群展示徽章'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='displayed_by_title', to='dreams.achievement', verbose_name='社群展示稱號'),
        ),
    ]
