# Generated by Django 5.1.7 on 2025-03-25 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0002_dream_emotion_score_dream_stress_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DreamAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dream_content", models.TextField(verbose_name="夢境內容")),
                (
                    "key_emotions",
                    models.JSONField(blank=True, null=True, verbose_name="關鍵情緒"),
                ),
                (
                    "psychological_interpretation",
                    models.TextField(blank=True, null=True, verbose_name="心理解讀"),
                ),
                (
                    "symbolic_meaning",
                    models.TextField(blank=True, null=True, verbose_name="象徵意義"),
                ),
                (
                    "stress_index",
                    models.IntegerField(default=0, verbose_name="壓力指數"),
                ),
                (
                    "anxiety_score",
                    models.FloatField(default=0, verbose_name="焦慮分數"),
                ),
                (
                    "health_recommendations",
                    models.TextField(
                        blank=True, null=True, verbose_name="心理健康建議"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "夢境分析",
                "verbose_name_plural": "夢境分析",
                "ordering": ["-created_at"],
            },
        ),
    ]
