# Generated by Django 5.1.6 on 2025-09-15 12:10

import dreams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0003_alter_userprofile_proof_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to=dreams.models.therapist_proof_upload_path, verbose_name='證明檔案'),
        ),
    ]
