# Generated by Django 5.1.6 on 2025-07-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0003_userprofile_display_badge_userprofile_display_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='current_badge_icon',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='current_title',
        ),
    ]
