# Generated by Django 5.1.6 on 2025-07-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0004_remove_userprofile_current_badge_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coin_price',
            field=models.PositiveIntegerField(default=10, help_text='每次預約所需點券數'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_badge_icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='當前徽章圖標'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='當前稱號'),
        ),
    ]
