# Generated by Django 5.1.6 on 2025-08-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0005_userprofile_coin_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/', verbose_name='檔案'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sticker',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='貼圖'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
