# Generated by Django 5.1.6 on 2025-03-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0007_remove_dreampost_ai_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="dream",
            name="advice",
            field=models.TextField(
                blank=True, null=True, verbose_name="心理診斷個人化建議"
            ),
        ),
    ]
