# Generated by Django 5.1.6 on 2025-08-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0009_dailytaskrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='private_notes',
            field=models.TextField(blank=True, null=True, verbose_name='私密筆記'),
        ),
    ]
