# Generated by Django 5.1.6 on 2025-04-02 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0009_rename_anxiety_dream_anxiety_rename_fear_dream_fear_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dreampost",
            name="advice",
            field=models.TextField(
                blank=True, null=True, verbose_name="心理診斷個人化建議"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dreamrecommendation",
            unique_together={("user", "created_at")},
        ),
    ]
