# Generated by Django 5.1.6 on 2025-04-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0010_dreampost_advice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateTimeField()),
            ],
        ),
    ]
