# Generated by Django 5.1.6 on 2025-04-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0011_news"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="date",
        ),
        migrations.AddField(
            model_name="news",
            name="link",
            field=models.URLField(default="http://example.com"),
        ),
        migrations.AddField(
            model_name="news",
            name="summary",
            field=models.TextField(default="http://example.com"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
