# Generated by Django 5.1.6 on 2025-08-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0011_remove_userprofile_private_notes_dreamshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='private_notes',
            field=models.TextField(blank=True, null=True, verbose_name='私密筆記'),
        ),
    ]
