# Generated by Django 5.1.6 on 2025-07-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0011_achievement_userprofile_current_badge_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
