# Generated by Django 5.1.6 on 2025-04-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0012_remove_news_date_news_link_news_summary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="link",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="news",
            name="summary",
            field=models.TextField(blank=True),
        ),
    ]
