# Generated by Django 5.1.6 on 2025-08-18 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0012_userprofile_private_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='我的關注清單', max_length=100, verbose_name='清單名稱')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '關注清單',
                'verbose_name_plural': '關注清單',
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='股票/指數代碼')),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dreams.watchlist', verbose_name='關注清單')),
            ],
            options={
                'verbose_name': '關注項目',
                'verbose_name_plural': '關注項目',
                'unique_together': {('watchlist', 'symbol')},
            },
        ),
    ]
