# Generated by Django 5.1.6 on 2025-08-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0013_watchlist_watchlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='偏好地區'),
        ),
    ]
