# Generated by Django 5.1.6 on 2025-07-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0014_pointorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointorder",
            name="points",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
