# Generated by Django 5.1.6 on 2025-07-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0015_pointorder_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointorder",
            name="item_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
