# Generated by Django 5.1.6 on 2025-07-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0017_delete_pointorder"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PointPackage",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="頭像"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, null=True, verbose_name="個人簡介"),
        ),
    ]
