# Generated by Django 5.1.6 on 2025-07-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0019_pointtransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapyappointment",
            name="point_change",
            field=models.IntegerField(default=0),
        ),
    ]
