# Generated by Django 5.1.6 on 2025-03-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('kpi_name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
