# Generated by Django 5.1.6 on 2025-03-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="grade",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
