# Generated by Django 5.1.7 on 2025-03-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_dream_comment_dreamanalysis_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="dream",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="dreamanalysis",
            name="dream",
        ),
        migrations.RemoveField(
            model_name="dreamentry",
            name="user",
        ),
        migrations.RemoveField(
            model_name="dreamkeyword",
            name="dream",
        ),
        migrations.DeleteModel(
            name="GlobalDreamTrend",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="dream",
            options={"verbose_name": "夢境", "verbose_name_plural": "夢境"},
        ),
        migrations.RemoveField(
            model_name="dream",
            name="content",
        ),
        migrations.RemoveField(
            model_name="dream",
            name="emotion_score",
        ),
        migrations.RemoveField(
            model_name="dream",
            name="title",
        ),
        migrations.RemoveField(
            model_name="dream",
            name="user",
        ),
        migrations.AddField(
            model_name="dream",
            name="dream_text",
            field=models.TextField(default="", verbose_name="夢境內容"),
        ),
        migrations.AddField(
            model_name="dream",
            name="interpretation",
            field=models.TextField(blank=True, verbose_name="心理學解析"),
        ),
        migrations.AddField(
            model_name="dream",
            name="keywords",
            field=models.TextField(blank=True, verbose_name="關鍵字"),
        ),
        migrations.AddField(
            model_name="dream",
            name="sentiment",
            field=models.CharField(blank=True, max_length=100, verbose_name="情緒指數"),
        ),
        migrations.AddField(
            model_name="dream",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新時間"),
        ),
        migrations.AlterField(
            model_name="dream",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="DreamAnalysis",
        ),
        migrations.DeleteModel(
            name="DreamEntry",
        ),
        migrations.DeleteModel(
            name="DreamKeyword",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
