# Generated by Django 5.1.6 on 2025-03-30 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0006_dreamtag_dreamtrend_dreampost_dreamcomment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dreampost",
            name="ai_analysis",
        ),
    ]
