# Generated by Django 5.1.6 on 2025-04-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0008_dream_advice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dream",
            old_name="anxiety",
            new_name="Anxiety",
        ),
        migrations.RenameField(
            model_name="dream",
            old_name="fear",
            new_name="Fear",
        ),
        migrations.RemoveField(
            model_name="dream",
            name="confusion",
        ),
        migrations.RemoveField(
            model_name="dream",
            name="hope",
        ),
        migrations.RemoveField(
            model_name="dream",
            name="surprise",
        ),
        migrations.AddField(
            model_name="dream",
            name="Excitement",
            field=models.FloatField(default=0, verbose_name="興奮 (%)"),
        ),
        migrations.AddField(
            model_name="dream",
            name="Happiness",
            field=models.FloatField(default=0, verbose_name="快樂 (%)"),
        ),
        migrations.AddField(
            model_name="dream",
            name="Sadness",
            field=models.FloatField(default=0, verbose_name="悲傷 (%)"),
        ),
        migrations.AlterField(
            model_name="dream",
            name="emotion_score",
            field=models.FloatField(default=0, verbose_name="情緒得分 (%)"),
        ),
    ]
