# Generated by Django 5.1.6 on 2025-05-26 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0013_alter_news_link_alter_news_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
