# Generated by Django 5.1.6 on 2025-07-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0016_achievement_userprofile_userachievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_badge_icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='當前徽章圖標'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='當前稱號'),
        ),
    ]
