# Generated by Django 5.1.6 on 2025-07-04 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0017_alter_userprofile_current_badge_icon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['condition_value'], 'verbose_name': '成就', 'verbose_name_plural': '成就'},
        ),
        migrations.AlterModelOptions(
            name='userachievement',
            options={'verbose_name': '用戶成就', 'verbose_name_plural': '用戶成就'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='badge_icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='徽章圖標'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(default='General', max_length=50, verbose_name='類別'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='condition_key',
            field=models.CharField(max_length=50, verbose_name='條件鍵'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='condition_value',
            field=models.IntegerField(default=1, verbose_name='條件值'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(verbose_name='成就描述'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='成就名稱'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='稱號'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreams.achievement', verbose_name='成就'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='unlocked_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='解鎖時間'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用戶'),
        ),
    ]
