# Generated by Django 5.1.6 on 2025-03-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SmartDash", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("task_name", models.CharField(max_length=255)),
                ("progress", models.IntegerField()),
                ("completed", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
