# Generated by Django 5.1.6 on 2025-03-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SmartDash", "0002_dashboarddata_delete_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashboarddata",
            name="completed",
        ),
        migrations.RemoveField(
            model_name="dashboarddata",
            name="date",
        ),
        migrations.RemoveField(
            model_name="dashboarddata",
            name="task_name",
        ),
        migrations.AddField(
            model_name="dashboarddata",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dashboarddata",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dashboarddata",
            name="progress",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
