# Generated by Django 5.1.6 on 2025-03-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SmartDash", "0003_remove_dashboarddata_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboarddata",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
