# Generated by Django 5.1.6 on 2025-03-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SmartDash", "0004_alter_dashboarddata_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dashboarddata",
            old_name="name",
            new_name="task_name",
        ),
        migrations.RemoveField(
            model_name="dashboarddata",
            name="description",
        ),
        migrations.AlterField(
            model_name="dashboarddata",
            name="progress",
            field=models.IntegerField(default=0),
        ),
    ]
