# Generated by Django 5.1.6 on 2025-03-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SmartDash", "0005_rename_name_dashboarddata_task_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboarddata",
            name="progress",
            field=models.FloatField(default=0.0),
        ),
    ]
