# Generated by Django 5.1.6 on 2025-03-04 20:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SmartDash", "0007_dashboarddata_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashboarddata",
            name="description",
        ),
        migrations.RemoveField(
            model_name="dashboarddata",
            name="progress",
        ),
        migrations.RemoveField(
            model_name="dashboarddata",
            name="task_name",
        ),
        migrations.AddField(
            model_name="dashboarddata",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="dashboarddata",
            name="kpi_name",
            field=models.CharField(
                choices=[
                    ("產量達成率", "產量達成率"),
                    ("工時效率", "工時效率"),
                    ("生產成本偏差率", "生產成本偏差率"),
                    ("銷售退貨率", "銷售退貨率"),
                    ("進貨單價", "進貨單價"),
                    ("委外加工退貨率", "委外加工退貨率"),
                    ("離職率", "離職率"),
                    ("庫存水位", "庫存水位"),
                ],
                default="產量達成率",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="dashboarddata",
            name="value",
            field=models.FloatField(default=0.0),
        ),
    ]
