# Generated by Django 5.1.6 on 2025-03-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SmartDash", "0008_remove_dashboarddata_description_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DashboardData",
            new_name="Dashboard",
        ),
        migrations.AlterModelTable(
            name="dashboard",
            table="dashboard",
        ),
    ]
