# Generated by Django 5.1.6 on 2025-06-30 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DreamTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="DreamTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("trend_data", models.JSONField(verbose_name="趨勢數據")),
            ],
            options={
                "verbose_name": "夢境趨勢",
                "verbose_name_plural": "夢境趨勢",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Dream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dream_content", models.TextField(verbose_name="夢境內容")),
                ("interpretation", models.TextField(verbose_name="解析結果")),
                (
                    "stress_index",
                    models.IntegerField(default=0, verbose_name="壓力指數"),
                ),
                (
                    "emotion_score",
                    models.FloatField(default=0, verbose_name="情緒得分 (%)"),
                ),
                ("Happiness", models.FloatField(default=0, verbose_name="快樂 (%)")),
                ("Anxiety", models.FloatField(default=0, verbose_name="焦慮 (%)")),
                ("Fear", models.FloatField(default=0, verbose_name="恐懼 (%)")),
                ("Excitement", models.FloatField(default=0, verbose_name="興奮 (%)")),
                ("Sadness", models.FloatField(default=0, verbose_name="悲傷 (%)")),
                (
                    "advice",
                    models.TextField(
                        blank=True, null=True, verbose_name="心理診斷個人化建議"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "夢境",
                "verbose_name_plural": "夢境",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DreamPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="夢境內容")),
                (
                    "title",
                    models.CharField(default="", max_length=100, verbose_name="標題"),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, verbose_name="匿名發布"),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="瀏覽次數")),
                (
                    "emotion_data",
                    models.JSONField(blank=True, default=dict, verbose_name="情緒數據"),
                ),
                (
                    "advice",
                    models.TextField(
                        blank=True, null=True, verbose_name="心理診斷個人化建議"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_flagged",
                    models.BooleanField(default=False, verbose_name="是否含有危險字詞"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="dreams.dreamtag", verbose_name="標籤"
                    ),
                ),
            ],
            options={
                "verbose_name": "夢境貼文",
                "verbose_name_plural": "夢境貼文",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DreamComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="評論內容")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dream_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="dreams.dreampost",
                    ),
                ),
            ],
            options={
                "verbose_name": "夢境評論",
                "verbose_name_plural": "夢境評論",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DreamRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recommended_dreams",
                    models.ManyToManyField(
                        related_name="recommended_to", to="dreams.dreampost"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "夢境推薦",
                "verbose_name_plural": "夢境推薦",
                "ordering": ["-created_at"],
                "unique_together": {("user", "created_at")},
            },
        ),
    ]
