# Generated by Django 5.1.7 on 2025-03-25 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0003_dreamanalysis"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DreamAnalysis",
        ),
    ]
