# Generated by Django 5.1.6 on 2025-03-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0004_delete_dreamanalysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="dream",
            name="anxiety",
            field=models.FloatField(default=0, verbose_name="焦慮 (%)"),
        ),
        migrations.AddField(
            model_name="dream",
            name="confusion",
            field=models.FloatField(default=0, verbose_name="困惑 (%)"),
        ),
        migrations.AddField(
            model_name="dream",
            name="fear",
            field=models.FloatField(default=0, verbose_name="恐懼 (%)"),
        ),
        migrations.AddField(
            model_name="dream",
            name="hope",
            field=models.FloatField(default=0, verbose_name="希望 (%)"),
        ),
        migrations.AddField(
            model_name="dream",
            name="surprise",
            field=models.FloatField(default=0, verbose_name="驚奇 (%)"),
        ),
    ]
