# Generated by Django 5.1.6 on 2025-06-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0004_remove_dreampost_is_flagged"),
    ]

    operations = [
        migrations.AddField(
            model_name="dreampost",
            name="is_flagged",
            field=models.BooleanField(default=False, verbose_name="是否含有危險字詞"),
        ),
    ]
