# Generated by Django 5.1.6 on 2025-07-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0012_userprofile_points"),
    ]

    operations = [
        migrations.CreateModel(
            name="PointPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("points_amount", models.IntegerField()),
                ("price", models.IntegerField()),
            ],
        ),
    ]
