# Generated by Django 5.1.6 on 2025-07-14 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0016_pointorder_item_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PointOrder",
        ),
    ]
