# Generated by Django 5.1.6 on 2025-03-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScamMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("risk_score", models.FloatField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("phishing", "釣魚詐騙"),
                            ("investment", "投資詐騙"),
                            ("shopping", "購物詐騙"),
                            ("loan", "貸款詐騙"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("keywords", models.TextField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=100, null=True)),
                ("is_verified_scam", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
